### ISSUE TITLE
AWS key and secret OR SMTP username and password

### ISSUE THREAD

**Issue by misbach** [bashaus/wp-mail-ses#1]
Your documentation makes it sound like I need to configure this plugin with my AWS key and secret. However the Amazon SES documentation states I need to use my SMTP username and password. Is that what I need to put into wp-config.php? Thanks!

**Comment by bashaus** [comment]
No need to configure the SMTP details. Just put your keys in the wp-config.php and you're good to go. Let me know if you have any issues.

**Comment by bashaus** [comment]
Closing issue as no response in 7 days. Assume fixed unless re-opened.
